tests: Use '--no-wait' to reduce clear/test_ust runtime
Motivation
==========

`regression/clear/test_ust` is one of the longer running regression
tests.

Solution
========

By using `--no-wait` when destroying sessions and reducing the value
of `DELAYUS` from the default of `1000000` (us) to `500000` (us) the
test runtime decreases from 5m48s to 4m36s on my development machine.

Known drawbacks
===============

When `DELAYUS` is further decreased, the events are no longer recorded
by the connected babeltrace live viewer.

Using `--no-wait` causes additional warnings and "errors" to be
emitted, which increase the effort required to find actual errors in
the test logs. For example,

```
PERROR - 12:07:59.932183981 [Rotation]: sendmsg: Broken pipe (in lttcomm_send_unix_sock() at unix.cpp:300)
Error: Failed to send result of the destruction of session
"s5yRHQuEBtpmQ8sF" to client
```

Change-Id: I58e71fe34cb4ee97e0879ebd5e08e6d9a1e6c07f
Signed-off-by: Kienan Stewart <kstewart@efficios.com>